### ISSUE TITLE
Errors when running scripts

### ISSUE THREAD

**Issue by sselgrad23** [VisualComputingInstitute/diffusion-e2e-ft#13]
Hi! Thank you for sharing your work! The results are impressive.

I was running the example code provided in the Quickstart section, and ran into the following errors: 
```
(.venv) (base) bla@bla:~/diffusion-e2e-ft$ python test.py
Traceback (most recent call last):
  File "/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 830, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/diffusers/loaders/unet.py", line 46, in <module>
    from .lora_pipeline import LORA_WEIGHT_NAME, LORA_WEIGHT_NAME_SAFE, TEXT_ENCODER_NAME, UNET_NAME
  File "/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/diffusers/loaders/lora_pipeline.py", line 33, in <module>
    from .lora_base import LoraBaseMixin
  File "/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/diffusers/loaders/lora_base.py", line 47, in <module>
    from peft.tuners.tuners_utils import BaseTunerLayer
  File "/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/peft/__init__.py", line 22, in <module>
    from .auto import (
  File "/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/peft/auto.py", line 32, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
  File "/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/peft/mapping.py", line 25, in <module>
    from .mixed_model import PeftMixedModel
  File "/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/peft/mixed_model.py", line 29, in <module>
    from .peft_model import PeftModel
  File "/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/peft/peft_model.py", line 37, in <module>
    from transformers import Cache, DynamicCache, EncoderDecoderCache, PreTrainedModel
ImportError: cannot import name 'EncoderDecoderCache' from 'transformers' (/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/transformers/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 830, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/diffusers/models/autoencoders/__init__.py", line 1, in <module>
    from .autoencoder_asym_kl import AsymmetricAutoencoderKL
  File "/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/diffusers/models/autoencoders/autoencoder_asym_kl.py", line 23, in <module>
    from .vae import DecoderOutput, DiagonalGaussianDistribution, Encoder, MaskConditionDecoder
  File "/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/diffusers/models/autoencoders/vae.py", line 25, in <module>
    from ..unets.unet_2d_blocks import (
  File "/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/diffusers/models/unets/__init__.py", line 6, in <module>
    from .unet_2d import UNet2DModel
  File "/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/diffusers/models/unets/unet_2d.py", line 24, in <module>
    from .unet_2d_blocks import UNetMidBlock2D, get_down_block, get_up_block
  File "/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/diffusers/models/unets/unet_2d_blocks.py", line 36, in <module>
    from ..transformers.dual_transformer_2d import DualTransformer2DModel
  File "/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/diffusers/models/transformers/__init__.py", line 13, in <module>
    from .prior_transformer import PriorTransformer
  File "/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/diffusers/models/transformers/prior_transformer.py", line 9, in <module>
    from ...loaders import PeftAdapterMixin, UNet2DConditionLoadersMixin
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 820, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 832, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.loaders.unet because of the following error (look up to see its traceback):
cannot import name 'EncoderDecoderCache' from 'transformers' (/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/transformers/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 830, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 44, in <module>
    from ..models import AutoencoderKL
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 820, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 832, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
Failed to import diffusers.loaders.unet because of the following error (look up to see its traceback):
cannot import name 'EncoderDecoderCache' from 'transformers' (/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/transformers/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bla/diffusion-e2e-ft/test.py", line 1, in <module>
    from diffusers import DiffusionPipeline
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 821, in __getattr__
    value = getattr(module, name)
  File "/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 820, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 832, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.pipelines.pipeline_utils because of the following error (look up to see its traceback):
Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
Failed to import diffusers.loaders.unet because of the following error (look up to see its traceback):
cannot import name 'EncoderDecoderCache' from 'transformers' (/home/bla/diffusion-e2e-ft/.venv/lib/python3.10/site-packages/transformers/__init__.py)
```

As recommended, I used Python 3.10 and installed the dependencies as demonstrated in the Development Setup section, and also installed torch, diffusers, transformers, and accelerate as listed in the Quickstart section. Below, you can see the modules installed in my environment:
```
(.venv) (base) bla@bla:~/diffusion-e2e-ft$ pip list
Package                  Version
------------------------ -----------
accelerate               0.27.2
aiohappyeyeballs         2.4.4
aiohttp                  3.11.10
aiosignal                1.3.2
annotated-types          0.7.0
antlr4-python3-runtime   4.9.3
async-timeout            5.0.1
attrs                    24.2.0
certifi                  2024.12.14
charset-normalizer       3.4.0
click                    8.1.7
contourpy                1.3.1
cycler                   0.12.1
datasets                 3.2.0
diffusers                0.30.2
dill                     0.3.8
docker-pycreds           0.4.0
filelock                 3.16.1
fonttools                4.55.3
frozenlist               1.5.0
fsspec                   2024.9.0
gitdb                    4.0.11
GitPython                3.1.43
h5py                     3.12.1
huggingface-hub          0.26.5
idna                     3.10
importlib_metadata       8.5.0
Jinja2                   3.1.4
kiwisolver               1.4.7
MarkupSafe               3.0.2
matplotlib               3.10.0
mpmath                   1.3.0
multidict                6.1.0
multiprocess             0.70.16
networkx                 3.4.2
numpy                    1.26.4
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.19.3
nvidia-nvjitlink-cu12    12.4.127
nvidia-nvtx-cu12         12.1.105
omegaconf                2.3.0
opencv-python            4.10.0.84
packaging                24.2
pandas                   2.2.3
peft                     0.14.0
pillow                   11.0.0
pip                      22.0.2
platformdirs             4.3.6
propcache                0.2.1
protobuf                 5.29.1
psutil                   6.1.0
pyarrow                  18.1.0
pydantic                 2.10.3
pydantic_core            2.27.1
pyparsing                3.2.0
python-dateutil          2.9.0.post0
pytz                     2024.2
PyYAML                   6.0.2
regex                    2024.11.6
requests                 2.32.3
safetensors              0.4.5
scipy                    1.14.1
sentry-sdk               2.19.2
setproctitle             1.3.4
setuptools               59.6.0
six                      1.17.0
smmap                    5.0.1
sympy                    1.13.1
tabulate                 0.9.0
tokenizers               0.15.2
torch                    2.2.0
torchvision              0.17.0
tqdm                     4.67.1
transformers             4.37.2
triton                   2.2.0
typing_extensions        4.12.2
tzdata                   2024.2
urllib3                  2.2.3
wandb                    0.19.1
xformers                 0.0.24
xxhash                   3.5.0
yarl                     1.18.3
zipp                     3.21.0
```

I also ran into these errors when running the commands listed in the Inference section ("python Marigold/run.py \ ..."). 

If you help me with solving these issues, I would greatly appreciate it!

**Comment by GonzaloMartinGarcia** [comment]
Hi,

Thank you for your kind words,

I was able to replicate the issue, and it appears to stem from a version mismatch between `transformers` and `peft`. On my setup, `peft==0.13.0` is installed, whereas your environment seems to have `peft==0.14.0`. 

Downgrading `peft` version to `0.13.0` should resolve this:

```bash
pip install --upgrade peft==0.13.0
```

We will update our requirements.txt to include specific version constraints for the `peft` library to prevent similar issues in the future.

Regards
