### ISSUE TITLE
OSError: prs-eth/marigold-v1-0 does not appear to have a file named scheduler_config.json.

### ISSUE THREAD

**Issue by Rander2002** [VisualComputingInstitute/diffusion-e2e-ft#16]
Hello, author: 
When I run `train.py,` the following error occurs. 

`ssh://root@10.28.16.76:30636/opt/conda/bin/python3.8 -u /212023081000012/ZMH/runde/diffusion-e2e-ft-main/training/train.py
Detected kernel version 3.10.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
12/25/2024 06:59:33 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: no

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/opt/conda/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/opt/conda/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f18d4526940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/opt/conda/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /prs-eth/marigold-v1-0/resolve/main/scheduler/scheduler_config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f18d4526940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1722, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(url=url, proxies=proxies, timeout=etag_timeout, headers=headers)
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1645, in get_hf_file_metadata
    r = _request_wrapper(
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 372, in _request_wrapper
    response = _request_wrapper(
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 395, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "/opt/conda/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/utils/_http.py", line 66, in send
    return super().send(request, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /prs-eth/marigold-v1-0/resolve/main/scheduler/scheduler_config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f18d4526940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"), '(Request ID: b236625f-c379-42e1-91aa-0609e34b5a65)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 379, in load_config
    config_file = hf_hub_download(
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1221, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1325, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1826, in _raise_on_head_call_error
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/212023081000012/ZMH/runde/diffusion-e2e-ft-main/training/train.py", line 639, in <module>
    main()
  File "/212023081000012/ZMH/runde/diffusion-e2e-ft-main/training/train.py", line 294, in main
    noise_scheduler = DDPMScheduler.from_pretrained(args.pretrained_model_name_or_path, subfolder="scheduler")
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/diffusers/schedulers/scheduling_utils.py", line 150, in from_pretrained
    config, kwargs, commit_hash = cls.load_config(
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 406, in load_config
    raise EnvironmentError(
OSError: prs-eth/marigold-v1-0 does not appear to have a file named scheduler_config.json.

Process finished with exit code 1
`

I roughly know that the problem is that my server cannot connect to the Internet, the network connection is wrong, so the model cannot find the corresponding model weights, but I can't enter huggingface.co. Do you have other addresses or ways to download the corresponding weight model?

**Comment by Rander2002** [comment]
I found the download link that can be accessed, and I have placed it below, which contains the weights of `marigold-v1-0` and `marigold-lcm-v1-0`:
`https://share.phys.ethz.ch/ ~pf/bingkedata/marigold/checkpoint/`

I am in the warehouse `https://github.com/prs-eth/Marigold/tree/main` I found it inside and mentioned the download address in the file `script/downloadw_weights. sh`. If there are similar errors, you can find the corresponding. sh file to check the download address

**Comment by karimknaebel** [comment]
glad that you could resolve the issue! :)
